### ISSUE TITLE
Specified module could not be found when installing Cartoframes

### ISSUE THREAD

**Issue by antoinecomp** [CartoDB/cartoframes#1320]
Following [this tutorial](https://carto.com/developers/cartoframes/guides/Installation/) I'm trying to install cartoframes. As far as [it isn't in anaconda](https://github.com/CartoDB/cartoframes/issues/363) I install it with pip. However, it returns:

```
(base) C:\Users\antoi\Documents\Programming\Richmond>python -m pip install cartoframes
Collecting cartoframes
  Using cached https://files.pythonhosted.org/packages/8b/d7/e373c29c93729836365ac453f6948216bf1e1d75d0d241ed3e9415e06fd2/cartoframes-0.10.1-py2.py3-none-any.whl
Collecting webcolors>=1.7 (from cartoframes)
  Using cached https://files.pythonhosted.org/packages/8b/ff/c21df7e08e68a1a84b947992c07dfed9cfe7219d068cb7728358d065c877/webcolors-1.10-py2.py3-none-any.whl
Collecting shapely>=1.5.0 (from cartoframes)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\antoi\\AppData\\Local\\Temp\\pip-install-9t9pwfit\\shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\antoi\\AppData\\Local\\Temp\\pip-install-9t9pwfit\\shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\antoi\AppData\Local\Temp\pip-install-9t9pwfit\shapely\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\antoi\AppData\Local\Temp\pip-install-9t9pwfit\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\antoi\AppData\Local\Temp\pip-install-9t9pwfit\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

Do you have any idea how to solve this issue?

**Comment by andy-esch** [comment]
Try installing one of the newer beta release:
```bash
$ pip install --pre cartoframes
```

The error you're getting looks specific to shapely, though, not cartoframes.
