### ISSUE TITLE
schema not always properly set in write operations

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#734]
Using `CartoContext().write` on cartoframes v0.10.0, the schema does not always resolve to the correct value. Strangely it works fine with my team account but fails for @jdgodchaux's team account.

The offending code is:
```python
cc.write(dataframe, 'tablename', lnglat=('Long', 'Lat'), overwrite=True)
```

We replaced it with this and it worked as expected (where the schema is manually set):
```python
d = Dataset.from_dataframe(dataframe)
d.upload(with_lnglat=('Long', 'Lat'), if_exists=Dataset.REPLACE, table_name='tablename', context=cc, schema=cc.get_default_schema())
```

The error:
```
Traceback (most recent call last):
  File "test-script.py", line 39, in <module>
    cc.write(dataframe, 'tablename', lnglat=('Long', 'Lat'), overwrite=True)
  File "/Users/jd/cfenv/lib/python3.7/site-packages/cartoframes/context.py", line 350, in write
    dataset = dataset.upload(with_lnglat=lnglat, if_exists=if_exists, table_name=table_name, context=self)
  File "/Users/jd/cfenv/lib/python3.7/site-packages/cartoframes/dataset.py", line 109, in upload
    self._create_table(with_lnglat)
  File "/Users/jd/cfenv/lib/python3.7/site-packages/cartoframes/dataset.py", line 162, in _create_table
    cartodbfy=self._cartodbfy_query()))
  File "/Users/jd/cfenv/lib/python3.7/site-packages/carto/sql.py", line 236, in create_and_wait_for_completion
    raise CartoException(_("Batch SQL job failed with result: {data}".format(data=data)))
carto.exceptions.CartoException: Batch SQL job failed with result: {'user': 'jdgodchaux-carto', 'status': 'failed', 'query': "BEGIN; DROP TABLE IF EXISTS sentinels; CREATE TABLE tablename (name text, euiui text, did text, lat numeric, long numeric, the_geom geometry(Point, 4326)); SELECT CDB_CartodbfyTable('public', 'tablename'); COMMIT;", 'created_at': '2019-06-04T16:26:41.785Z', 'updated_at': '2019-06-04T16:26:41.893Z', 'failed_reason': 'Please set user quota before cartodbfying tables.', 'job_id': 'f9dacf10-710f-490e-857a-7057bc950d9d'}
```

**Comment by djfan** [comment]
I got the same error when I `cc.write(geopandas.GeoDataFrames, 'dataset')`

**Comment by Jesus89** [comment]
This should be actually a `hotfix/patch` of the v0.10, right? Because this is a bug in the "old" API.

**Comment by oleurud** [comment]
0.10 is already published, I suppose we can not modify a released version and it would be 0.10.1

**Comment by Jesus89** [comment]
Yes, we should publish a 0.10.1 with this fix

**Comment by andy-esch** [comment]
Agree we should release 0.10.1

**Comment by Jesus89** [comment]
Closed via #762

**Comment by oleurud** [comment]
We should wait to close issues until the fix is released

**Comment by Jesus89** [comment]
OK

**Comment by oleurud** [comment]
Solved in version `0.10.1`

**Comment by andrewbt** [comment]
Is there any reason I would be running into this exact same error running `v0.10.1`?

```
from cartoframes.examples import read_brooklyn_poverty

cc.write(read_brooklyn_poverty(), 'brooklyn_poverty_example', overwrite=True)
```
results in:

```
Params: encode_geom, geom_col and everything in kwargs are deprecated and not being used any more
/local_disk0/pythonVirtualEnvDirs/virtualEnv-cb932e9e-40b9-4045-bedb-6d5ef08ea7a9/lib/python3.5/site-packages/carto/sql.py:229: UserWarning: Batch SQL job created with job_id: ec0870a0-713f-4ef3-80a0-15978ebf1329
  warnings.warn('Batch SQL job created with job_id: {job_id}'.format(job_id=data['job_id']))
CartoException: Batch SQL job failed with result: {'user': 'jefferies05', 'query': "BEGIN; DROP TABLE IF EXISTS brooklyn_poverty_example; CREATE TABLE brooklyn_poverty_example (total_pop_2011_2015 numeric, pop_determined_poverty_status_2011_2015 numeric, total_population numeric, commuters_16_over_2011_2015 numeric, poverty_per_pop numeric, geoid text, walked_to_work_2011_2015_per_pop numeric, poverty_count numeric, the_geom geometry(MultiPolygon, 4326)); SELECT CDB_CartodbfyTable('public', 'brooklyn_poverty_example'); COMMIT;", 'created_at': '2019-07-20T00:17:42.581Z', 'job_id': 'ec0870a0-713f-4ef3-80a0-15978ebf1329', 'updated_at': '2019-07-20T00:17:42.685Z', 'status': 'failed', 'failed_reason': 'Please set user quota before cartodbfying tables.'}
```

in very next cell, I run:

`cartoframes.__version__`
returning:
`Out[9]: '0.10.1'`

**Comment by andrewbt** [comment]
disregard, I reloaded my notebook and it seems to work now, so I'm going to chalk it up to some kind of caching issue or running my cells out of order and changing usernames.

Strange though as while I was debugging, `cc.is_org` was returning "false" when `cc` should have definitely been pointing to an org-type account, and `cc.get_default_schema()` was `public` (and not the proper `jefferies05` account I was using. I think that's why the batch job was failing because it was trying to write to `public.brooklyn_poverty_example` for some reason.

**Comment by oleurud** [comment]
> it was trying to write to public.brooklyn_poverty_example for some reason

Yes, it is usually the reason. If you see it again, please let us know, thank you
